PUT http://localhost:3010/cache/1
Content-Type: application/json

{
      "listsToShow": ["all", "Opiskelut", "empty"]
}

###
POST http://localhost:3010/lists
Content-Type: application/json

{
      "name": "testi"
}