PUT http://localhost:3010/todos/11
Content-Type: application/json

{
      "text": "testi",
      "due": "2021-25-20T21:00",
      "isDone": false,
      "list": "sekalaiset"
}

###
POST http://localhost:3010/lists
Content-Type: application/json

{
      "name": "testi"
}