PUT http://localhost:3010/cache/2
Content-Type: application/json

{
      "lists": {
                  "all": {
                        "id": "all",
                        "todoIds": [
                              "todo-1",
                              "todo-0"
                        ]
                  },
                  "Opiskelu": {
                        "id": "Opiskelu",
                        "todoIds": [
                              "todo-1",
                              "todo-0"
                        ]
                  }
      }
}

###
POST http://localhost:3010/lists
Content-Type: application/json

{
      "name": "testi"
}